### ISSUE TITLE
Couldn't see plex in the Browser

### ISSUE THREAD

**Issue by arunprasaddoss** [risiko79/mopidy_plex#1]
Hi,

thanks for great extension. I am having trouble setting it up.

My settings are 

- Plex Server - Free tier
- Mopidy running on Raspberry OS on raspberry pi 4
- Mopidy Musicbox-Webclient as frontend

I have installed the extension using the pip as using the .whl file

I have setup the configuration as follows:

```
[plex]
enabled = true
server = DietPi
token = 
username = arunrock13@gmail.com
password = ********
port = 32400
host = 192.168.33.183
```

I am not getting any error in Mopidy service. But I couldn't see plex in the Browser list. Not sure what I am doing wrong.

Kindly help me resolve this issue.

```
● mopidy.service - Mopidy music server
     Loaded: loaded (/lib/systemd/system/mopidy.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2022-01-09 18:48:24 IST; 2min 26s ago
    Process: 1418 ExecStartPre=/bin/mkdir -p /var/cache/mopidy (code=exited, status=0/SUCCESS)
    Process: 1419 ExecStartPre=/bin/chown mopidy:audio /var/cache/mopidy (code=exited, status=0/SUCCESS)
   Main PID: 1420 (mopidy)
      Tasks: 20 (limit: 3720)
        CPU: 5.421s
     CGroup: /system.slice/mopidy.service
             └─1420 /usr/bin/python3 /usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf

Jan 09 18:48:25 RadioPi mopidy[1420]: INFO     [MainThread] mopidy.commands Starting Mopidy mixer: SoftwareMixer
Jan 09 18:48:25 RadioPi mopidy[1420]: INFO     [MainThread] mopidy.commands Starting Mopidy audio
Jan 09 18:48:25 RadioPi mopidy[1420]: INFO     [MainThread] mopidy.commands Starting Mopidy backends: LocalBackend, FileBackend, M3UBackend, StreamBackend, PodcastBackend
Jan 09 18:48:25 RadioPi mopidy[1420]: WARNING  [MainThread] mopidy_local.storage Local media dir /media/DietPi/Entertainment/Music does not exist or we lack permissions to the directory or one of its parents
Jan 09 18:48:25 RadioPi mopidy[1420]: INFO     [Audio-2] mopidy.audio.actor Audio output set to "autoaudiosink"
Jan 09 18:48:25 RadioPi mopidy[1420]: INFO     [MainThread] mopidy.commands Starting Mopidy core
Jan 09 18:48:25 RadioPi mopidy[1420]: INFO     [MainThread] mopidy.commands Starting Mopidy frontends: IrisFrontend, HttpFrontend
Jan 09 18:48:25 RadioPi mopidy[1420]: INFO     [IrisFrontend-9] mopidy_iris.core Starting Iris 3.60.1
Jan 09 18:48:25 RadioPi mopidy[1420]: INFO     [HttpFrontend-11] mopidy.http.actor HTTP server running at [::ffff:0.0.0.0]:6680
Jan 09 18:48:25 RadioPi mopidy[1420]: INFO     [MainThread] mopidy.commands Starting GLib mainloop
```

**Comment by risiko79** [comment]
Hi. 
1. Please leave the port and host empty - this is the client config not for the server connection
2. Your PlexServer name is  really DietPi
3. Please configurate mopity to log into a file 
```
[logging]
config_file ='<path>/logging.conf
```

logging.conf example:
```
[loggers]
keys = root,plex

[handlers]
keys = file,fileplex

[formatters]
keys = simple

[logger_root]
handlers = file

[handler_file]
class = handlers.RotatingFileHandler
formatter = simple
level = INFO
args = ('<path>/mopidy.log','a',100000,10,)

[handler_fileplex]
class = handlers.RotatingFileHandler
formatter = simple
level = DEBUG
args = ('<path>/mopidy_plex.log','a',100000,10,)

[formatter_simple]
format = %(asctime)s %(levelname)s %(name)s(%(lineno)d): %(message)s

[logger_plex]
level = DEBUG
handlers = fileplex 
qualname = mopidy_plex
propagate = 1
```

**Comment by arunprasaddoss** [comment]
I have made the changes to the logging and the config. I am getting "plexapi" unable to import error


`2022-01-16 10:53:29,149 INFO mopidy.config(192): Loading config from file:///usr/share/mopidy/conf.d/mopidy.conf
2022-01-16 10:53:29,149 INFO mopidy.config(192): Loading config from file:///etc/mopidy/mopidy.conf
2022-01-16 10:53:29,150 INFO mopidy.config(170): Loading config from command line options
2022-01-16 10:53:29,528 INFO mopidy.__main__(187): Enabled extensions: plex, local, stream, softwaremixer, http, podcast, mpd, >
2022-01-16 10:53:29,528 INFO mopidy.__main__(188): Disabled extensions: none
2022-01-16 10:53:29,649 ERROR mopidy.__main__(135): Extension plex failed during setup. This might have left the registry in a >
Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/mopidy/__main__.py", line 129, in main
    extension.setup(registry)
  File "/usr/local/lib/python3.9/dist-packages/mopidy_plex/__init__.py", line 39, in setup
    from .backend import PlexBackend
  File "/usr/local/lib/python3.9/dist-packages/mopidy_plex/backend.py", line 15, in <module>
    from .library import PlexLibraryProvider
  File "/usr/local/lib/python3.9/dist-packages/mopidy_plex/library.py", line 8, in <module>
    from plexapi import audio as plexaudio
ModuleNotFoundError: No module named 'plexapi'

2022-01-16 10:53:29,711 INFO mopidy.commands(380): Starting Mopidy mixer: SoftwareMixer
2022-01-16 10:53:29,714 INFO mopidy.commands(399): Starting Mopidy audio
2022-01-16 10:53:29,717 INFO mopidy.commands(403): Starting Mopidy backends: LocalBackend, FileBackend, M3UBackend, StreamBacke>
2022-01-16 10:53:29,736 INFO mopidy.audio.actor(135): Audio output set to "autoaudiosink"`

I have installed plex api and able to import from my python Command Line. Kindly help

**Comment by risiko79** [comment]
Please restart the mopidy service and check if the same error occurs. 
What version of plexapi did you installed and under which user?
Do the mopidy service run as from the same user you installed plexapi?

**Comment by arunprasaddoss** [comment]
Hi,

Thanks a lot for your support.

As you suggested the issue was with the plexapi installed user. I switched to root user and installed it once again. Which resolved the issue.

Now I am able to enjoy my music from my plex server. Thanks again.
